//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integrador.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string ButtonAssignCar {
            get {
                return ResourceManager.GetString("ButtonAssignCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ButtonRemoveCar {
            get {
                return ResourceManager.GetString("ButtonRemoveCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CarDelete {
            get {
                return ResourceManager.GetString("CarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate.
        /// </summary>
        internal static string CarLicensePlate {
            get {
                return ResourceManager.GetString("CarLicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        internal static string CarMake {
            get {
                return ResourceManager.GetString("CarMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string CarNew {
            get {
                return ResourceManager.GetString("CarNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string CarPrice {
            get {
                return ResourceManager.GetString("CarPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string CarSave {
            get {
                return ResourceManager.GetString("CarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string CarYear {
            get {
                return ResourceManager.GetString("CarYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Assignment Manager.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Cars.
        /// </summary>
        internal static string LabelAssignedCars {
            get {
                return ResourceManager.GetString("LabelAssignedCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Cars.
        /// </summary>
        internal static string LabelAvailableCars {
            get {
                return ResourceManager.GetString("LabelAvailableCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person&apos;s Cars.
        /// </summary>
        internal static string LabelPersonCars {
            get {
                return ResourceManager.GetString("LabelPersonCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        internal static string LabelPersons {
            get {
                return ResourceManager.GetString("LabelPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string PersonCarsQuantity {
            get {
                return ResourceManager.GetString("PersonCarsQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string PersonDelete {
            get {
                return ResourceManager.GetString("PersonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string PersonFirstname {
            get {
                return ResourceManager.GetString("PersonFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Card.
        /// </summary>
        internal static string PersonIdentityCard {
            get {
                return ResourceManager.GetString("PersonIdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string PersonLastname {
            get {
                return ResourceManager.GetString("PersonLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string PersonNew {
            get {
                return ResourceManager.GetString("PersonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string PersonSave {
            get {
                return ResourceManager.GetString("PersonSave", resourceCulture);
            }
        }
    }
}
